# Site settings
course_name: CS290: Seminar on Effective Research Practices and Academic Culture
course_description: "This is a reading and discussion-based seminar designed for entering Computer Science Ph.D. students. This course prepares students to manage the difficult and often undiscussed challenges of Ph.D. programs through sessions on research skill building (e.g. paper reading, communication), soft skill building (e.g. managing advising relationships, supporting your peers), and academic culture (e.g. mental health in academia, power dynamics in scientific communities), as well as research and professional-oriented discussions. This is a full-year, 4-unit course, meeting once a week in each of the fall and the spring. Students must complete both terms of this course (parts A and B) within the same academic year to receive credit."
course_semester: "Fall 2022 - Spring 2023"

baseurl: "/harvard-cs290-new" # the subpath of your site, e.g. /blog/
url: "https://yanivyacoby.github.io/" # the base hostname & protocol for your site

schoolname: "Harvard University"
schoolurl: "https://www.seas.harvard.edu/"
twitter_username:  

address: |
    John A. Paulson School of Engineering and Applied Sciences
    Harvard University
    Science and Engineering Complex
    150 Western Ave, Boston, MA 02134

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: false
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
